version: '3'

services:
  eureka:
    image: continuity/eureka
    hostname: eureka
    networks:
      - continuity-network
    ports:
      - '8761:8761'
  frontend:
    image: continuity/frontend
    hostname: frontend
    networks:
      - continuity-network
    ports:
      - '8080:80'
    depends_on:
      - rabbitmq
      - eureka
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    networks:
      - continuity-network
  workload-annotation:
    image: continuity/workload-annotation
    hostname: workload-annotation
    networks:
      - continuity-network
    ports:
      - '8081:80'
    depends_on:
      - rabbitmq
      - eureka
  wessbas:
    image: continuity/wessbas
    hostname: wessbas
    networks:
      - continuity-network
    ports:
      - '8082:80'
    depends_on:
      - rabbitmq
      - eureka
  jmeter:
    image: continuity/jmeter
    hostname: jmeter
    networks:
      - continuity-network
    ports:
      - '8083:80'
    depends_on:
      - rabbitmq
      - eureka
  session-logs:
    image: continuity/session-logs
    hostname: session-logs
    networks:
      - continuity-network
    ports:
      - '8084:80'
    depends_on:
      - rabbitmq
      - eureka

networks:
  continuity-network:
    driver: bridge