server:
  port: ${port:0}
spring:
  application:
    name: workload-annotation
  rabbitmq:
    host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.uri:http://localhost:8761/eureka}
  instance:
    statusPageUrlPath: /swagger-ui.html
    preferIpAddress: true